# Główne źródło finansowania (bez prowizji GitHuba!)
github: ITomPoland

# [Na Przyszłość] Jeśli załozysz Ko-Fi albo Buy Me a Coffee:
# ko_fi: ITomPoland
# buy_me_a_coffee: ITomPoland

# Customowe linki
custom: 
  - https://github.com/sponsors/ITomPoland
  # - https://www.awwwards.com/ITomPoland # Mega patent: gdy będziesz miał profil na Awwwards, wrzuć go tu!
